import { createKarakter } from '../core/create-karakter';
import { ember } from '../core/data/fajok';
import { sajatKultura } from '../core/data/hatterek';
import { harcmuveszHarcUtjaKardmuvesz } from '../core/data/iskolak';
import { fajdalomtures, harciLaz, harcmuveszet, harcteriGyakorlat, vertviselet } from '../core/data/kepzettsegek';
import { Karakter } from '../core/models/karakter';
import { TulajdonsagType } from '../core/models/tulajdonsag';

test('Character: Dreg Darra', () => {
  const dregDarra = createKarakter({
    nev: 'Dreg Darra',
    hatterek: [ember, sajatKultura('erv', 'közös'), harcmuveszHarcUtjaKardmuvesz],
    tulajdonsagok: {
      ero: 14,
      gyorsasag: 14,
      ugyesseg: 14,
      allokepesseg: 15,
      karizma: 9,
      egeszseg: 15,
      intelligencia: 9,
      akaratero: 14,
      asztral: 18,
      erzekeles: 13,
    },
    szintlepesek: [
      {
        kepzettsegek: [
          { kepzettseg: fajdalomtures, kp: 6 },
          { kepzettseg: harcmuveszet('Slan kard'), kp: 13, tulajdonsag: TulajdonsagType.Gyorsasag },
          { kepzettseg: harcteriGyakorlat, kp: 15, tulajdonsag: TulajdonsagType.Gyorsasag },
          { kepzettseg: vertviselet, kp: 6 },
        ],
        fp: 10,
      },
      {
        kepzettsegek: [
          { kepzettseg: harcmuveszet('Slan tőr'), kp: 13, tulajdonsag: TulajdonsagType.Gyorsasag },
          { kepzettseg: harcmuveszet('Shien-su'), kp: 27, tulajdonsag: TulajdonsagType.Gyorsasag },
        ],
        fp: 1,
      },
      {
        kepzettsegek: [{ kepzettseg: harciLaz, kp: 28, tulajdonsag: TulajdonsagType.Egeszseg }],
        fp: 9,
        te: 2,
      },
      { fp: 1, te: 20 },
    ],
  });

  const expected: Karakter = {
    nev: 'Dreg Darra',
    jellem: '',
    faj: 'ember',
    kaszt: ['Harcművész (Harc útja Kardművész)'],
    szintenkentiKap: 41,
    hatterek: { 'Pszi érzékenység': 1 },
    szint: 4,
    tulajdonsagLimitek: {
      ero: 18,
      gyorsasag: 18,
      ugyesseg: 18,
      allokepesseg: 18,
      egeszseg: 18,
      karizma: 18,
      intelligencia: 18,
      akaratero: 18,
      asztral: 18,
      erzekeles: 18,
    },
    tulajdonsagok: {
      ero: 14,
      gyorsasag: 18,
      ugyesseg: 14,
      allokepesseg: 15,
      karizma: 9,
      egeszseg: 16,
      intelligencia: 9,
      akaratero: 14,
      asztral: 18,
      erzekeles: 13,
    },
    maxEp: 16,
    maxFp: 54,
    maxPszi: 13,
    maxMana: 0,
    maxKegy: 0,
    ke: 31,
    te: 76,
    ce: 32,
    ve: 92,
    asztralTME: 18,
    mentalTME: 14,
    szintenkentiAsztralTME: 0,
    szintenkentiMentalTME: 0,
    szintenkentiKegy: 0,
    szintenkentiPszi: 1,
    szintenkentiFp: 1,
    oktatasok: {
      Akrobatika: 2,
      Élettan: 2,
      Esés: 2,
      Fájdalomtűrés: 2,
      Fegyverismeret: 2,
      Futás: 2,
      Harcművészet: 2,
      'Harctéri gyakorlat': 2,
      Herbalizmus: 2,
      'Írás/Olvasás': 2,
      Kétkezesharc: 2,
      Kultúra: 2,
      Művészetek: 2,
      Nyelvtudás: 2,
      Orvoslás: 2,
      Párbaj: 2,
      'Pszi (Slan Út)': 2,
      'Udvari etikett/intrika': 2,
      Vakharc: 2,
      Vértviselet: 2,
      Fegyverhasználat: 1,
      Hadvezetés: 1,
      'Harci láz': 1,
      Pajzshasználat: 1,
      'Pusztakezes harc': 1,
      Pusztítás: 1,
      Taktika: 1,
      Térképészet: 1,
      Lélektan: 1,
      'Számtan/Mértan': 1,
      'Jog/Törvénykezés': 1,
      Történelem: 1,
      Vallásismeret: 1,
      Állatismeret: 1,
      Lovaglás: 1,
    },
    kepzettsegek: {
      'Harcművészet (Slan kard)': 4,
      'Harcművészet (Slan tőr)': 4,
      'Pszi (Slan Út)': 3,
      'Írás/Olvasás': 1,
      Orvoslás: 2,
      Élettan: 2,
      Herbalizmus: 2,
      Esés: 10,
      Akrobatika: 10,
      'Kultúra (erv)': 3,
      'Nyelvtudás (közös)': 3,
      'Helyismeret (erv)': 3,
      Fájdalomtűrés: 3,
      'Harctéri gyakorlat': 4,
      Vértviselet: 3,
      'Harcművészet (Shien-su)': 4,
      'Harci láz': 5,
    },
  };

  expect(dregDarra).toEqual(expected);
});
