import { expect, test } from 'vitest';
import { createKarakter } from '../core/create-karakter';
import { ember } from '../core/data/fajok';
import { adottsag, sajatKultura } from '../core/data/hatterek';
import { paplovagDomvik } from '../core/data/iskolak';
import {
  fajdalomtures,
  fegyverhasznalat,
  harcteriGyakorlat,
  kultura,
  nyelvtudas,
  pajzshasznalat,
  vallasismeret,
  vertviselet,
} from '../core/data/kepzettsegek';
import { Karakter } from '../core/models/karakter';
import { TulajdonsagType } from '../core/models/tulajdonsag';

// TODO: MGT miatt nem passzol a teszt

test('Character: Bor Ven - lvl 5', () => {
  const bor = createKarakter({
    nev: 'Bor Ven',
    jellem: 'Rend, Élet',
    hatterek: [
      ember,
      sajatKultura('shadoni'),
      adottsag(TulajdonsagType.Ugyesseg, 1),
      paplovagDomvik({ fegyverhasznalat3: 'lovagkard' }),
    ],
    tulajdonsagok: {
      ero: 14,
      gyorsasag: 14,
      ugyesseg: 14,
      allokepesseg: 14,
      karizma: 9,
      egeszseg: 14,
      intelligencia: 14,
      akaratero: 14,
      asztral: 14,
      erzekeles: 14,
    },
    szintlepesek: [
      {
        kepzettsegek: [
          { kepzettseg: nyelvtudas('shadoni'), kp: 5 },
          { kepzettseg: kultura('shadoni'), kp: 5 },
          { kepzettseg: vallasismeret('Domvik'), kp: 8, tulajdonsag: TulajdonsagType.Intelligencia },
          { kepzettseg: fajdalomtures, kp: 11, tulajdonsag: TulajdonsagType.Allokepesseg },
          { kepzettseg: harcteriGyakorlat, kp: 11, tulajdonsag: TulajdonsagType.Gyorsasag },
        ],
        kegy: 1,
        fp: 10,
        te: 2,
      },
      {
        kepzettsegek: [
          { kepzettseg: nyelvtudas('shadoni'), kp: 10 },
          { kepzettseg: kultura('shadoni'), kp: 10 },
          { kepzettseg: vallasismeret('Domvik'), kp: 11 },
        ],
        kegy: 3,
        te: 2,
      },
      {
        kepzettsegek: [
          { kepzettseg: pajzshasznalat, kp: 21, tulajdonsag: TulajdonsagType.Ero },
          { kepzettseg: vertviselet, kp: 18, tulajdonsag: TulajdonsagType.Ero },
          { kepzettseg: nyelvtudas('közös'), kp: 2 },
        ],
        te: 2,
      },
      {
        kepzettsegek: [{ kepzettseg: fegyverhasznalat('lovagkard'), tulajdonsag: TulajdonsagType.Ero, kp: 14 }],
        kegy: 6,
        te: 6,
      },
      { te: 7, fp: 30 },
    ],
  });

  const expected: Karakter = {
    nev: 'Bor Ven',
    jellem: 'Rend, Élet',
    faj: 'ember',
    kaszt: ['Paplovag (Domvik)'],
    szintenkentiKap: 40,
    hatterek: {
      Kegyelt: 1,
      'Adottság (ugyesseg)': 1,
    },
    szint: 5,
    tulajdonsagLimitek: {
      ero: 18,
      gyorsasag: 18,
      ugyesseg: 19,
      allokepesseg: 18,
      egeszseg: 18,
      karizma: 18,
      intelligencia: 18,
      akaratero: 18,
      asztral: 18,
      erzekeles: 18,
    },
    tulajdonsagok: {
      ero: 17,
      gyorsasag: 15,
      ugyesseg: 15,
      allokepesseg: 15,
      karizma: 9,
      egeszseg: 14,
      intelligencia: 15,
      akaratero: 14,
      asztral: 14,
      erzekeles: 14,
    },
    maxEp: 14,
    maxFp: 77,
    maxPszi: 0,
    maxMana: 0,
    maxKegy: 24,
    ke: 27,
    te: 62,
    ce: 30,
    ve: 90,
    asztralTME: 28,
    mentalTME: 28,
    szintenkentiAsztralTME: 3,
    szintenkentiMentalTME: 3,
    szintenkentiKegy: 3,
    szintenkentiPszi: 0,
    szintenkentiFp: 2,
    szintenkentiHm: 2,
    oktatasok: {
      Állatismeret: 2,
      Ékesszólás: 2,
      Élettan: 2,
      Fegyverhasználat: 2,
      Fegyverismeret: 2,
      Fájdalomtűrés: 2,
      'Harctéri gyakorlat': 2,
      Heraldika: 2,
      Herbalizmus: 2,
      'Írás/Olvasás': 2,
      'Jog/Törvénykezés': 2,
      Kultúra: 2,
      Legendaismeret: 2,
      Lélektan: 2,
      Lovaglás: 2,
      Művészetek: 2,
      Nyelvtudás: 2,
      Orvoslás: 2,
      'Ősi nyelv (lingua domini)': 2,
      Pajzshasználat: 2,
      'Politika/diplomácia': 2,
      'Pszi (pyarroni)': 2,
      'Számtan/Mértan': 2,
      Térképészet: 2,
      Történelem: 2,
      'Udvari etikett/intrika': 2,
      Vallásismeret: 2,
      Vértviselet: 2,
      Hadvezetés: 2,
    },
    kepzettsegek: {
      Fájdalomtűrés: 4,
      'Fegyverhasználat (lovagkard)': 4,
      Hadvezetés: 2,
      'Harctéri gyakorlat': 4,
      Pajzshasználat: 5,
      Vértviselet: 5,
      'Állatismeret (hátas állatok)': 2,
      Lovaglás: 3,
      Élettan: 2,
      Herbalizmus: 2,
      'Írás/Olvasás': 2,
      Orvoslás: 2,
      'Ősi nyelv (lingua domini)': 2,
      Történelem: 2,
      'Vallásismeret (Domvik)': 5,
      Ékesszólás: 2,
      Heraldika: 2,
      Lélektan: 2,
      'Helyismeret (shadoni)': 3,
      'Kultúra (shadoni)': 5,
      'Nyelvtudás (shadoni)': 5,
      'Nyelvtudás (közös)': 2,
      'Politika/diplomácia': 2,
      'Udvari etikett/intrika': 2,
    },
  };

  expect(bor).toEqual(expected);
});
