import { expect, test } from 'vitest';
import { createKarakter } from '../core/create-karakter';
import { ember } from '../core/data/fajok';
import { adottsag, sajatKultura, sugallat } from '../core/data/hatterek';
import { abaszisziFalanxharcos } from '../core/data/iskolak';
import {
  elettan,
  fajdalomtures,
  fegyverhasznalat,
  harcteriGyakorlat,
  herbalizmus,
  irasOlvasas,
  nyelvtudas,
  orvoslas,
  pusztitas,
  taktika,
  vertviselet,
} from '../core/data/kepzettsegek';
import { Karakter } from '../core/models/karakter';
import { TulajdonsagType } from '../core/models/tulajdonsag';

test('Character: Arkhal Katur - lvl 4', () => {
  const bor = createKarakter({
    nev: 'Arkhal Katur',
    jellem: 'Rend, Élet',
    hatterek: [
      ember,
      sajatKultura('abasziszi', 'aszisz', 'Abaszisz'),
      abaszisziFalanxharcos,
      adottsag(TulajdonsagType.Ero, 3),
      sugallat,
    ],
    tulajdonsagok: {
      ero: 14,
      gyorsasag: 17,
      ugyesseg: 14,
      allokepesseg: 15,
      karizma: 9,
      egeszseg: 15,
      intelligencia: 11,
      akaratero: 15,
      asztral: 9,
      erzekeles: 16,
    },
    szintlepesek: [
      {
        kepzettsegek: [
          { kepzettseg: fajdalomtures, kp: 11, tulajdonsag: TulajdonsagType.Ero },
          { kepzettseg: harcteriGyakorlat, kp: 21, tulajdonsag: TulajdonsagType.Ugyesseg },
          { kepzettseg: nyelvtudas('közös'), kp: 8 },
        ],
        te: 4,
        fp: 11,
      },
      {
        kepzettsegek: [
          { kepzettseg: fegyverhasznalat('lándzsa'), kp: 28, tulajdonsag: TulajdonsagType.Ero },
          { kepzettseg: taktika, kp: 8, tulajdonsag: TulajdonsagType.Erzekeles },
        ],
        te: 6,
      },
      {
        kepzettsegek: [
          { kepzettseg: irasOlvasas, kp: 8 },
          { kepzettseg: herbalizmus, kp: 1 },
          { kepzettseg: orvoslas, kp: 2 },
          { kepzettseg: elettan, kp: 17 },
          { kepzettseg: vertviselet, kp: 8, tulajdonsag: TulajdonsagType.Ero },
        ],
        te: 4,
        fp: 4,
      },
      {
        kepzettsegek: [{ kepzettseg: pusztitas, kp: 30, tulajdonsag: TulajdonsagType.Ero }],
        te: 7,
        fp: 4,
      },
    ],
  });

  const expected: Karakter = {
    nev: 'Arkhal Katur',
    jellem: 'Rend, Élet',
    faj: 'ember',
    kaszt: ['Abasziszi falanxharcos'],
    szintenkentiKap: 42,
    hatterek: {
      'Adottság (ero)': 3,
      Sugallat: 1,
    },
    szint: 4,
    tulajdonsagLimitek: {
      ero: 20,
      gyorsasag: 18,
      ugyesseg: 18,
      allokepesseg: 18,
      egeszseg: 18,
      karizma: 18,
      intelligencia: 18,
      akaratero: 18,
      asztral: 18,
      erzekeles: 18,
    },
    tulajdonsagok: {
      ero: 20,
      gyorsasag: 17,
      ugyesseg: 15,
      allokepesseg: 15,
      karizma: 9,
      egeszseg: 15,
      intelligencia: 11,
      akaratero: 15,
      asztral: 9,
      erzekeles: 17,
    },
    maxEp: 15,
    maxFp: 57,
    maxPszi: 0,
    maxMana: 0,
    maxKegy: 0,
    ke: 34,
    te: 73,
    ce: 32,
    ve: 92,
    asztralTME: 9,
    mentalTME: 15,
    szintenkentiAsztralTME: 0,
    szintenkentiMentalTME: 0,
    szintenkentiKegy: 0,
    szintenkentiPszi: 0,
    szintenkentiFp: 2,
    szintenkentiHm: 3,
    oktatasok: {
      Esés: 2,
      'Fegyverhasználat (egykezes kardok)': 2,
      'Fegyverhasználat (lándzsa)': 2,
      'Fegyverhasználat (rövidkard)': 2,
      Fegyverismeret: 2,
      Futás: 2,
      Fájdalomtűrés: 2,
      Hadvezetés: 2,
      'Harctéri gyakorlat': 2,
      Lélektan: 2,
      'Művészetek (rajz)': 2,
      'Nyelvtudás (aszisz)': 2,
      Pajzshasználat: 2,
      'Pusztakezes harc': 2,
      'Számtan/Mértan': 2,
      Taktika: 2,
      Térképészet: 2,
      Vértviselet: 2,
      'Írás/Olvasás': 2,
      Úszás: 2,
    },
    kepzettsegek: {
      Esés: 20,
      'Fegyverhasználat (egykezes kardok)': 2,
      'Fegyverhasználat (lándzsa)': 5,
      Fegyverismeret: 2,
      Futás: 2,
      Fájdalomtűrés: 4,
      'Harctéri gyakorlat': 5,
      'Helyismeret (Abaszisz)': 3,
      Herbalizmus: 1,
      'Kultúra (abasziszi)': 3,
      'Nyelvtudás (aszisz)': 3,
      'Nyelvtudás (közös)': 3,
      Orvoslás: 1,
      Pajzshasználat: 3,
      'Pusztakezes harc (ökölharc)': 2,
      Pusztítás: 4,
      Taktika: 4,
      Vértviselet: 4,
      Élettan: 3,
      'Írás/Olvasás': 2,
      Úszás: 2,
    },
  };

  expect(bor).toEqual(expected);
});
